dist: bionic
sudo: true
language: java
script: clj -A:test
install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.466.sh
  - chmod +x linux-install-1.10.1.466.sh
  - sudo ./linux-install-1.10.1.466.sh
env:
  global:
    - CI_BUILD=1
  matrix:
    - BOOT_CLOJURE_VERSION=1.8.0
jdk:
  - openjdk8
  - openjdk10
  - openjdk11
cache:
  directories:
  - $HOME/.m2
  - .cpcache