dist: xenial
sudo: true
language: java
script: clojure -A:test
install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.763.sh
  - chmod +x linux-install-1.10.1.763.sh
  - sudo ./linux-install-1.10.1.763.sh
env:
  global:
    - CI_BUILD=1
jdk:
  - openjdk11
cache:
  directories:
  - $HOME/.m2
  - .cpcache
