name: Caffeinated Ideas
description: Random thoughts on tech, beer and games after too much coffee.
url: http://caffeinatedideas.com

timezone: America/Los_Angeles
future: false
lsi: false
encoding: "UTF-8"
