name: CI Workflow
on: [push, pull_request]
jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: vouch-opensource/tools.deps-build@1.0.1
      with:
        alias: :test
